# Generated by Django 5.0.6 on 2024-06-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_vendor_tablet_smartphone_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='book.vendor'),
        ),
    ]
